apiVersion: apps/v1
kind: Application
metadata:
  name: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: playground
        image: wil42/playground:v1
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-service
  labels:
    app: test-app
spec:
  selector:
    app: test-app
  ports:
    - port: 80
      targetPort: 8888
  type: LoadBalancer
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: test-app
#   namespace: dev
# spec:
#   destination:
#     namespace: dev
#     server: https://kubernetes.default.svc
#   containers:
#     name: playground
#     image: wil42/playground:v1
